version: "2"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    networks:
      - default
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
  mysql:
        image: mysql:5.7.13
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
        networks:
            - default
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - mysql:db
        ports:
            - 8001:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "myDb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8002:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "vip.prokopets@mail.ru"     
      PGADMIN_DEFAULT_PASSWORD: "admin"
